// projectStore.js — in-memory copy of the open project's data, with dirty
// tracking and saving back through the preload API.
import { api } from "./api.js";
import { DATA_FILES, blankMap, mapInfo, defaultSystem } from "./defaultData.js";

export function mapFileName(id) {
    return "Map" + String(id).padStart(3, "0") + ".json";
}

export function parsePluginsJs(text) {
    const start = text.indexOf("[");
    const end = text.lastIndexOf("]");
    if (start < 0 || end < start) return [];
    try {
        return JSON.parse(text.slice(start, end + 1));
    } catch (e) {
        // Some MZ files contain trailing commas; strip them and retry.
        return JSON.parse(text.slice(start, end + 1).replace(/,\s*([\]}])/g, "$1"));
    }
}

export function formatPluginsJs(plugins) {
    const lines = plugins.map(p => JSON.stringify(p));
    return "// Generated by RPG Maker 9000.\n// Edit plugins with Tools > Plugin Manager (F10).\nvar $plugins =\n[\n" + lines.join(",\n") + "\n];\n";
}

// Fill in System fields that older or MV-era projects lack (e.g. "advanced",
// "titleCommandWindow") so editor tabs can rely on them. Existing values win.
export function fillSystemDefaults(system) {
    const defaults = defaultSystem(system.gameTitle);
    for (const [key, value] of Object.entries(defaults)) {
        if (system[key] === undefined || system[key] === null) {
            system[key] = value;
        } else if (value && typeof value === "object" && !Array.isArray(value) && typeof system[key] === "object" && !Array.isArray(system[key])) {
            for (const [sub, subValue] of Object.entries(value)) {
                if (system[key][sub] === undefined) system[key][sub] = subValue;
            }
        }
    }
    return system;
}

export class ProjectStore {
    constructor(bus) {
        this.bus = bus;
        this.reset();
    }

    reset() {
        this.dir = null;
        this.data = {};
        this.maps = new Map();
        this.plugins = [];
        this.dirty = new Set();
        this.deletedMaps = new Set();
    }

    get isOpen() {
        return !!this.dir;
    }

    get system() {
        return this.data.System;
    }

    async open(dir) {
        this.reset();
        const data = {};
        for (const name of DATA_FILES) {
            try {
                data[name] = await api.fs.readJson("data/" + name + ".json");
            } catch (e) {
                data[name] = name === "System" ? null : [null];
            }
        }
        if (!data.System) throw new Error("data/System.json is missing or invalid.");
        fillSystemDefaults(data.System);
        this.dir = dir;
        this.data = data;
        try {
            this.plugins = parsePluginsJs(await api.fs.readText("js/plugins.js"));
        } catch (e) {
            this.plugins = [];
        }
        this.bus.emit("project-opened", this);
    }

    close() {
        this.reset();
        this.bus.emit("project-closed");
    }

    async loadMap(id) {
        if (this.maps.has(id)) return this.maps.get(id);
        let map;
        try {
            map = await api.fs.readJson("data/" + mapFileName(id));
        } catch (e) {
            map = blankMap(17, 13, 1);
        }
        if (!map.events) map.events = [null];
        this.maps.set(id, map);
        return map;
    }

    getMap(id) {
        return this.maps.get(id) || null;
    }

    markDirty(key) {
        this.dirty.add(key);
        this.bus.emit("dirty-changed", true);
    }

    isDirty() {
        return this.dirty.size > 0 || this.deletedMaps.size > 0;
    }

    async save() {
        if (!this.isOpen) return;
        // Snapshot the previous on-disk state first (throttled in main).
        if (this.dirty.size || this.deletedMaps.size) {
            try {
                await api.project.backup();
            } catch (e) {
                console.warn("Backup failed:", e);
            }
        }
        for (const key of [...this.dirty]) {
            if (key.startsWith("Map:")) {
                const id = Number(key.slice(4));
                const map = this.maps.get(id);
                if (map) await api.fs.writeJson("data/" + mapFileName(id), map);
            } else if (key === "plugins") {
                await api.fs.writeText("js/plugins.js", formatPluginsJs(this.plugins));
            } else if (this.data[key] !== undefined) {
                await api.fs.writeJson("data/" + key + ".json", this.data[key]);
            }
        }
        for (const id of this.deletedMaps) await api.fs.delete("data/" + mapFileName(id));
        this.dirty.clear();
        this.deletedMaps.clear();
        this.bus.emit("dirty-changed", false);
        this.bus.emit("project-saved");
    }

    // --- maps ---------------------------------------------------------------

    mapInfos() {
        return this.data.MapInfos;
    }

    nextMapId() {
        const infos = this.mapInfos();
        for (let id = 1; id < infos.length; id++) if (!infos[id]) return id;
        return infos.length;
    }

    childrenOf(parentId) {
        return this.mapInfos()
            .filter(info => info && info.parentId === parentId)
            .sort((a, b) => a.order - b.order);
    }

    // Recomputes `order` so it follows a depth-first walk of the tree.
    renumberOrders() {
        let order = 1;
        const walk = parentId => {
            for (const info of this.childrenOf(parentId)) {
                info.order = order++;
                walk(info.id);
            }
        };
        walk(0);
        this.markDirty("MapInfos");
    }

    createMap(parentId, options = {}) {
        const id = this.nextMapId();
        const infos = this.mapInfos();
        const name = options.name || "MAP" + String(id).padStart(3, "0");
        infos[id] = mapInfo(id, name, parentId, 9999);
        const tilesetId = options.tilesetId || this.defaultTilesetId();
        const map = options.map || blankMap(options.width || 17, options.height || 13, tilesetId);
        this.maps.set(id, map);
        this.deletedMaps.delete(id);
        this.renumberOrders();
        this.markDirty("Map:" + id);
        this.bus.emit("maps-changed");
        return id;
    }

    defaultTilesetId() {
        const t = this.data.Tilesets.find(t => t && t.name);
        return t ? t.id : 1;
    }

    // Deletes a map and all its descendants. Returns removed ids.
    deleteMap(id) {
        const infos = this.mapInfos();
        const removed = [];
        const walk = mapId => {
            for (const child of this.childrenOf(mapId)) walk(child.id);
            infos[mapId] = null;
            this.maps.delete(mapId);
            this.dirty.delete("Map:" + mapId);
            this.deletedMaps.add(mapId);
            removed.push(mapId);
        };
        walk(id);
        while (infos.length > 1 && infos[infos.length - 1] === null) infos.pop();
        this.renumberOrders();
        this.bus.emit("maps-changed");
        return removed;
    }

    // Moves a map in the tree. where: "before" | "after" | "into".
    moveMap(id, targetId, where) {
        const infos = this.mapInfos();
        const info = infos[id];
        if (!info || id === targetId) return;
        // Prevent moving a map into its own descendant.
        for (let p = targetId; p; p = infos[p] ? infos[p].parentId : 0) if (p === id) return;
        if (where === "into") {
            info.parentId = targetId;
            info.order = 99999;
        } else {
            const target = infos[targetId];
            info.parentId = target ? target.parentId : 0;
            info.order = target ? target.order + (where === "before" ? -0.5 : 0.5) : 99999;
        }
        this.renumberOrders();
        this.bus.emit("maps-changed");
    }

    setPlugins(list) {
        this.plugins = list;
        this.markDirty("plugins");
        this.bus.emit("plugins-changed");
    }
}
